version: '2'
services:
  compose-sql-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    container_name: compose-sql-db
    environment:
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: "Y"
  api:
    build:
      context: .
      dockerfile: EfCoreDockerCompose/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - SqlServerConnectionString=$SQLServerConnectionString
    depends_on:
      - compose-sql-db
